/* UI copy. Hand-maintained - NOT editable in the CMS.
   Projects and news live in content/ and are generated into data.js by build.py. */
var T = {
 "en": {
  "skip": "Skip to content",
  "brandSub": "Besloten Vennootschap",
  "nav1": "Services",
  "nav6": "Sectors",
  "nav2": "Projects",
  "nav3": "Approach",
  "nav4": "About",
  "nav5": "Contact",
  "heroEyebrow": "Independent energy engineering &middot; Belgium",
  "heroH1a": "Every installation,",
  "heroH1b": "verified.",
  "heroLede": "Energy Experts BV delivers independent electrical design, classification and inspection for offshore wind, solar and industrial power systems across Belgium, France and Spain.",
  "ctaA": "Request an inspection",
  "ctaB": "See our work",
  "plateHd": "Company data plate",
  "plateLive": "Active",
  "pk1": "Established",
  "pk2": "Registered",
  "pk3": "Standards",
  "pk4": "Disciplines",
  "pv4": "Wind &middot; Solar &middot; HV/LV",
  "pk5": "Coverage",
  "pk6": "Response",
  "pv6": "2 working days",
  "stripLbl": "Working to",
  "svcEyebrow": "Services",
  "svcH2": "Three disciplines, one dossier",
  "svcSub": "Every assignment ends in a conformity file your inspection body and your insurer will accept.",
  "s1h": "Electrical design &amp; classification",
  "s1p": "Design review, conformity assessment and zone classification for LV and HV installations under AREI/RGIE.",
  "s1a": "Single-line diagram review",
  "s1b": "Protection coordination study",
  "s1c": "Technical dossier preparation",
  "s2h": "Offshore wind",
  "s2p": "Commissioning support, electrical inspection and QA/QC witness for turbines, array cables and offshore substations.",
  "s2a": "Array cable termination witness",
  "s2b": "HV commissioning support",
  "s2c": "Punch list close-out",
  "s3h": "Solar PV inspection",
  "s3p": "Thermographic survey, string and insulation testing, and IEC 62446 commissioning reports for rooftop and utility-scale arrays.",
  "s3a": "Drone and handheld thermography",
  "s3b": "String I-V curve tracing",
  "s3c": "Yield underperformance analysis",
  "secEyebrow": "Sectors",
  "secH2": "Where we work",
  "secSub": "Four environments, each with its own rulebook and its own failure modes.",
  "x1h": "Offshore &amp; marine",
  "x1p": "Wind farms, export cables and offshore substations in the Belgian and Dutch North Sea.",
  "x2h": "Utility-scale solar",
  "x2p": "Ground-mount parks from 1 MWp upward across France, Spain and the Benelux.",
  "x3h": "Industry &amp; logistics",
  "x3p": "Distribution boards, transformer rooms and HV cabins in plants and warehouses.",
  "x4h": "Grid &amp; substations",
  "x4p": "Connection studies and conformity classification up to 150 kV.",
  "prjEyebrow": "Project register",
  "prjH2": "Recent assignments",
  "prjSub": "Select any row to open the full scope and technical summary.",
  "th1": "Project",
  "th2": "Location",
  "th3": "Rating",
  "th4": "Scope",
  "th5": "Year",
  "regNote": "Sample entries &mdash; you add, edit and remove these yourself, without a developer.",
  "appEyebrow": "Method",
  "appH2": "How an assignment runs",
  "appSub": "Four stages, from first drawing to a cleared installation.",
  "n1": "Stage 01",
  "a1h": "Intake",
  "a1p": "We collect single-line diagrams, protection settings and as-built documentation before anyone mobilises.",
  "n2": "Stage 02",
  "a2h": "Field measurement",
  "a2p": "On site: insulation resistance, earthing continuity, thermography and torque verification.",
  "n3": "Stage 03",
  "a3h": "Conformity dossier",
  "a3p": "Findings compiled into a report written to be accepted first time by your inspection body.",
  "n4": "Stage 04",
  "a4h": "Clearance",
  "a4p": "Remediation advice and re-inspection until the installation is signed off.",
  "abEyebrow": "About us",
  "abH2": "Engineers, not auditors.",
  "abP1": "We are a small Belgian practice of chartered electrical engineers working across North Sea wind, industrial power and utility-scale solar. Every assignment is carried out by the engineer who signs the report.",
  "abP2": "Independence is the product. We hold no supplier relationships and we install nothing, so our findings answer to the standard and to you.",
  "k1": "Inspections completed",
  "k2": "Capacity assessed",
  "k3": "Countries",
  "k4": "In practice",
  "r1": "Managing director",
  "b1": "Chartered electrical engineer. Twenty years in HV commissioning across the North Sea.",
  "r2": "Head of inspection",
  "b2": "Leads AREI/RGIE conformity work and signs the technical dossiers.",
  "r3": "Solar lead, Iberia",
  "b3": "IEC 62446 commissioning and thermographic survey across Spain and southern France.",
  "qT": "They found a protection setting error two other parties had signed off. The report was accepted by our inspection body without a single query.",
  "qN": "Project director",
  "qC": "offshore wind developer, Ostend",
  "faqEyebrow": "Questions",
  "faqH2": "Before you call",
  "q1": "How quickly can you mobilise?",
  "an1": "For installations in Belgium, typically within five working days. Offshore assignments are planned around the vessel window and are agreed in advance.",
  "q2": "Do you issue the official certificate?",
  "an2": "No, and that is deliberate. We prepare the conformity dossier and correct the findings so that the accredited inspection body can certify without objection. Keeping those roles separate is what makes the file credible.",
  "q3": "Which languages do you report in?",
  "an3": "Dutch, French, English and Spanish. The report is delivered in the language your inspection body works in.",
  "q4": "Do you work outside Belgium?",
  "an4": "Regularly. Roughly half our solar work is in France and Spain, and offshore assignments cover the Belgian and Dutch North Sea.",
  "ctEyebrow": "Contact",
  "ctH2": "Tell us about the installation.",
  "ctP": "Send the basics and we will come back within two working days with a scope and a price.",
  "c1": "Office",
  "c2": "Telephone",
  "c3": "Email",
  "c4": "Hours",
  "c4v": "Mon&ndash;Fri, 08:00&ndash;17:00 CET",
  "f1": "Name",
  "f2": "Company",
  "f3": "Email",
  "f4": "Service",
  "o1": "Electrical classification",
  "o2": "Offshore wind",
  "o3": "Solar PV inspection",
  "o4": "Something else",
  "f5": "Describe the installation",
  "f6": "I agree that Energy Experts BV may store and use these details to answer my enquiry, as described in the privacy policy.",
  "f7": "Send enquiry",
  "f8": "Demo form &mdash; nothing is sent",
  "mapH": "Where to find us",
  "mapP": "Our office in Grimbergen, just north of Brussels.",
  "mapB": "Open in Maps",
  "brandSub2": "Besloten Vennootschap",
  "fEnt": "Enterprise no.",
  "fVat": "VAT",
  "fNav": "Site",
  "nav1b": "Services",
  "nav6b": "Sectors",
  "nav2b": "Projects",
  "nav3b": "Approach",
  "fComp": "Company",
  "nav4b": "About",
  "fFaq": "FAQ",
  "nav5b": "Contact",
  "fCareer": "Careers",
  "fLegal": "Legal",
  "fl1": "Privacy policy",
  "fl3": "Terms &amp; conditions",
  "fl4": "Complaints",
  "fCk": "Cookie settings",
  "fBtm": "Design concept &middot; placeholder content",
  "ckH": "We keep this simple",
  "ckP": "This site sets no cookies and loads nothing from other companies. We only want to remember your language and your light or dark choice in this browser. Read the <a href=\"#\">privacy policy</a>.",
  "ckAll": "Accept all",
  "ckNone": "Reject all",
  "ckCust": "Choose what loads",
  "pfH": "What loads on this site",
  "pfP": "Nothing in the second and third group loads until you switch it on. You can change this at any time from the footer.",
  "pf1h": "Strictly necessary",
  "pf1p": "Nothing. This site needs no cookie in order to work.",
  "pf2h": "Remember language and theme",
  "pf2p": "Stores your language and your light or dark choice in this browser. Never shared.",
  "pf3h": "Statistics",
  "pf3p": "Anonymous visit counts so we know which pages are read. No cookie, no personal data.",
  "pfSave": "Save choices",
  "pfAll": "Accept all",
  "mDur": "Duration",
  "mScope": "Scope delivered",
  "sent": "Thank you — in a live site this would now be in your inbox.",
  "errName": "Please add your name.",
  "errMail": "Please check the email address.",
  "errMsg": "Please describe the installation.",
  "errConsent": "Please tick the consent box.",
  "h1v2a": "Independent eyes on",
  "h1v2b": "every megawatt.",
  "h1v3": "The report your inspection body accepts first time.",
  "h1v4a": "Verified at sea.",
  "h1v4b": "Certified on land.",
  "ledeShort": "Independent electrical design, classification and inspection. Belgium, France, Spain.",
  "tagline": "Independent electrical inspection · Belgium",
  "since": "Since 2016",
  "locBadge": "Grimbergen · Belgium",
  "whH": "Why Energy Experts",
  "whSub": "Three things we will not compromise on.",
  "wh1h": "Independent by design",
  "wh1p": "We install nothing and sell nothing. Our only product is the finding.",
  "wh2h": "Engineer-signed",
  "wh2p": "The engineer on site is the engineer who signs. No hand-offs, no juniors.",
  "wh3h": "Four languages, one standard",
  "wh3p": "Reports in the language of your inspection body — NL, FR, EN or ES.",
  "nwH": "Insights",
  "nwSub": "Notes from the field.",
  "nwAll": "All insights",
  "readMore": "Read",
  "nw1t": "Why 66 kV array cables fail at the termination",
  "nw1d": "Reading the tan delta curve before it becomes a warranty claim.",
  "nw1m": "Offshore · 6 min",
  "nw2t": "AREI/RGIE 2025: what changed for HV cabins",
  "nw2d": "The revised zone classification rules, explained for site managers.",
  "nw2m": "Regulation · 4 min",
  "nw3t": "Thermography is not an inspection",
  "nw3d": "A hot spot is a symptom. The I-V trace tells you the cause.",
  "nw3m": "Solar · 5 min",
  "crH": "Join the practice",
  "crP": "We are looking for a chartered electrical engineer with HV commissioning experience, based in Belgium and comfortable working in Dutch and French.",
  "crB": "See open positions",
  "ctaH": "Have an installation waiting on sign-off?",
  "ctaP": "Send us the single-line diagram. Within two working days we will tell you what it takes to clear it.",
  "ctaBtn": "Start an enquiry",
  "ctaSmall": "Get in touch",
  "certH": "Accreditations",
  "cert1": "BelAC-recognised inspection partner",
  "cert2": "VCA / LSC safety certified",
  "cert3": "ISO 9001 quality management",
  "cert4": "GWO Basic Safety Training, offshore",
  "cap1": "Norther offshore wind farm, Belgian North Sea",
  "cap2": "Thorntonbank wind farm, aerial",
  "cap3": "Cable-lay vessel, C-Power",
  "cap4": "Ground-mount PV array",
  "cap5": "150 kV switchgear",
  "cap6": "Offshore turbine installation",
  "viewAll": "View all projects",
  "scrollHint": "Scroll",
  "learn": "Learn more",
  "photoCredits": "Photo credits",
  "k5": "Reports issued",
  "mClose": "Close",
  "designLabel": "Design",
  "abH3": "About Energy Experts",
  "msH": "Our mission",
  "msP": "To make every installation we touch safer, simpler to certify and cheaper to insure — by putting an independent engineer between the contractor and the sign-off.",
  "ptH": "Partners who trust us",
  "ptSub": "Developers, grid operators and EPC contractors across the Benelux and France.",
  "certBtn": "Our certifications",
  "moreInfo": "More information",
  "getInTouch": "Get in touch",
  "polH": "Our guidelines for responsibility and integrity",
  "polSub": "Three documents every client, partner and employee can hold us to.",
  "pol1h": "HSE policy",
  "pol1s": "Health, Safety & Environment",
  "pol1p": "How we plan, work and report on site so that nobody gets hurt and nothing is spilled.",
  "pol2h": "Human rights policy",
  "pol2s": "Labour & supply chain",
  "pol2p": "Our commitments on labour, equal treatment and the supply chain, aligned with the UN Guiding Principles.",
  "pol3h": "Code of conduct",
  "pol3s": "Independence & anti-corruption",
  "pol3p": "Independence, confidentiality and anti-corruption rules that every engineer signs on their first day.",
  "polDl": "Download PDF",
  "cr1h": "Do pioneering work",
  "cr1p": "66 kV arrays, floating foundations, hybrid PV-storage: the installations you inspect will not be in any textbook yet.",
  "cr2h": "International environment",
  "cr2p": "Belgian North Sea one week, a solar park in Aragón the next. Four working languages in the office.",
  "cr3h": "Growth and development",
  "cr3p": "GWO, HV switching authorisation and chartered status — funded and scheduled from your first year.",
  "vacancies": "Vacancies",
  "fFirst": "First name",
  "fLast": "Last name",
  "fCountry": "Country code",
  "fPhone": "Phone number",
  "prjRef": "Project references",
  "tbHint": "Tap a blade to open a project",
  "tbNext": "Next project",
  "tbPrev": "Previous",
  "tbOpen": "Open case file",
  "tbAuto": "Rotates on its own · hover or tap to pause",
  "prjMore": "Find out more about our projects.",
  "cta2H": "Ready for your next project?",
  "cta2P": "One call is enough to scope it. We will tell you honestly whether you need us.",
  "locH": "Location of our team",
  "fSocial": "Follow us",
  "ptDev": "Developer",
  "ptDev2": "Developer",
  "ptDev3": "Developer",
  "ptGrid": "Grid operator",
  "ptMarine": "Marine contractor",
  "ptEpc": "Offshore EPC",
  "ptUtil": "Utility",
  "ptUtil2": "Utility",
  "ptNote": "Placeholder names — replaced with your real clients once they agree to be listed."
 },
 "fr": {
  "skip": "Aller au contenu",
  "brandSub": "Société à responsabilité limitée",
  "brandSub2": "Société à responsabilité limitée",
  "nav1": "Services",
  "nav2": "Projets",
  "nav3": "Méthode",
  "nav4": "À propos",
  "nav5": "Contact",
  "nav6": "Secteurs",
  "nav1b": "Services",
  "nav2b": "Projets",
  "nav3b": "Méthode",
  "nav4b": "À propos",
  "nav5b": "Contact",
  "nav6b": "Secteurs",
  "heroEyebrow": "Ingénierie énergétique indépendante · Belgique",
  "heroH1a": "Chaque installation,",
  "heroH1b": "vérifiée.",
  "heroLede": "Energy Experts BV réalise la conception, la classification et l’inspection électriques indépendantes pour l’éolien offshore, le solaire et les installations industrielles en Belgique, en France et en Espagne.",
  "ctaA": "Demander une inspection",
  "ctaB": "Voir nos projets",
  "plateHd": "Fiche signalétique",
  "plateLive": "En activité",
  "pk1": "Créée",
  "pk2": "Siège",
  "pk3": "Normes",
  "pk4": "Disciplines",
  "pk5": "Couverture",
  "pk6": "Réponse",
  "pv4": "Éolien · Solaire · HT/BT",
  "pv6": "2 jours ouvrables",
  "stripLbl": "Conforme à",
  "svcEyebrow": "Services",
  "svcH2": "Trois disciplines, un seul dossier",
  "svcSub": "Chaque mission aboutit à un dossier de conformité accepté par votre organisme agréé et votre assureur.",
  "s1h": "Conception et classification électriques",
  "s1p": "Revue de conception, évaluation de conformité et classification des zones pour installations BT et HT selon le RGIE.",
  "s1a": "Revue des schémas unifilaires",
  "s1b": "Étude de sélectivité des protections",
  "s1c": "Constitution du dossier technique",
  "s2h": "Éolien offshore",
  "s2p": "Assistance à la mise en service, inspection électrique et témoin QA/QC pour éoliennes, câbles inter-éoliennes et postes offshore.",
  "s2a": "Témoin de raccordement des câbles",
  "s2b": "Assistance mise en service HT",
  "s2c": "Clôture des réserves",
  "s3h": "Inspection photovoltaïque",
  "s3p": "Thermographie, essais de chaînes et d’isolement, rapports de mise en service IEC 62446 pour toitures et centrales au sol.",
  "s3a": "Thermographie par drone et manuelle",
  "s3b": "Relevé de courbes I-V",
  "s3c": "Analyse des sous-performances",
  "secEyebrow": "Secteurs",
  "secH2": "Où nous intervenons",
  "secSub": "Quatre environnements, chacun avec ses règles et ses modes de défaillance.",
  "x1h": "Offshore et maritime",
  "x1p": "Parcs éoliens, câbles d’export et postes en mer du Nord belge et néerlandaise.",
  "x2h": "Solaire à grande échelle",
  "x2p": "Centrales au sol à partir de 1 MWc en France, en Espagne et au Benelux.",
  "x3h": "Industrie et logistique",
  "x3p": "Tableaux de distribution, locaux transformateurs et cabines HT en usine et en entrepôt.",
  "x4h": "Réseau et postes",
  "x4p": "Études de raccordement et classification de conformité jusqu’à 150 kV.",
  "prjEyebrow": "Registre des projets",
  "prjH2": "Missions récentes",
  "prjSub": "Sélectionnez une ligne pour ouvrir le périmètre complet et la fiche technique.",
  "th1": "Projet",
  "th2": "Lieu",
  "th3": "Puissance",
  "th4": "Prestation",
  "th5": "Année",
  "regNote": "Exemples — vous ajoutez, modifiez et supprimez ces entrées vous-même, sans développeur.",
  "appEyebrow": "Méthode",
  "appH2": "Le déroulement d’une mission",
  "appSub": "Quatre étapes, du premier schéma à l’installation validée.",
  "n1": "Étape 01",
  "n2": "Étape 02",
  "n3": "Étape 03",
  "n4": "Étape 04",
  "a1h": "Prise en charge",
  "a1p": "Nous rassemblons schémas unifilaires, réglages de protection et plans as-built avant toute mobilisation.",
  "a2h": "Mesures sur site",
  "a2p": "Sur place : résistance d’isolement, continuité des terres, thermographie et vérification des couples de serrage.",
  "a3h": "Dossier de conformité",
  "a3p": "Constats compilés dans un rapport rédigé pour être accepté du premier coup par votre organisme agréé.",
  "a4h": "Validation",
  "a4p": "Conseils de remédiation et contre-visite jusqu’à la réception de l’installation.",
  "abEyebrow": "À propos",
  "abH2": "Des ingénieurs, pas des auditeurs.",
  "abP1": "Nous sommes un bureau belge d’ingénieurs électriciens agréés intervenant dans l’éolien en mer du Nord, l’énergie industrielle et le solaire à grande échelle. Chaque mission est menée par l’ingénieur qui signe le rapport.",
  "abP2": "L’indépendance est notre produit. Nous n’avons aucun lien avec les fournisseurs et n’installons rien : nos constats ne répondent qu’à la norme et à vous.",
  "k1": "Inspections réalisées",
  "k2": "Puissance évaluée",
  "k3": "Pays",
  "k4": "D’expérience",
  "r1": "Directeur général",
  "r2": "Responsable inspection",
  "r3": "Responsable solaire, Ibérie",
  "b1": "Ingénieur électricien agréé. Vingt ans de mise en service HT en mer du Nord.",
  "b2": "Pilote les travaux de conformité RGIE et signe les dossiers techniques.",
  "b3": "Mise en service IEC 62446 et thermographie en Espagne et dans le sud de la France.",
  "qT": "Ils ont trouvé une erreur de réglage de protection que deux autres intervenants avaient validée. Le rapport a été accepté par notre organisme agréé sans une seule question.",
  "qN": "Directeur de projet",
  "qC": "développeur éolien offshore, Ostende",
  "faqEyebrow": "Questions",
  "faqH2": "Avant de nous appeler",
  "q1": "Sous quel délai pouvez-vous intervenir ?",
  "an1": "Pour les installations en Belgique, généralement sous cinq jours ouvrables. Les missions offshore sont planifiées selon la fenêtre navire et convenues à l’avance.",
  "q2": "Délivrez-vous le certificat officiel ?",
  "an2": "Non, et c’est délibéré. Nous constituons le dossier de conformité et corrigeons les constats afin que l’organisme agréé puisse certifier sans objection. Séparer ces rôles est ce qui rend le dossier crédible.",
  "q3": "Dans quelles langues rédigez-vous les rapports ?",
  "an3": "Néerlandais, français, anglais et espagnol. Le rapport est remis dans la langue de travail de votre organisme agréé.",
  "q4": "Intervenez-vous hors de Belgique ?",
  "an4": "Régulièrement. Près de la moitié de nos missions solaires se déroulent en France et en Espagne, et l’offshore couvre la mer du Nord belge et néerlandaise.",
  "ctEyebrow": "Contact",
  "ctH2": "Parlez-nous de votre installation.",
  "ctP": "Envoyez l’essentiel : nous revenons vers vous sous deux jours ouvrables avec un périmètre et un prix.",
  "c1": "Bureau",
  "c2": "Téléphone",
  "c3": "E-mail",
  "c4": "Horaires",
  "c4v": "Lun–ven, 08h00–17h00 CET",
  "f1": "Nom",
  "f2": "Société",
  "f3": "E-mail",
  "f4": "Prestation",
  "f5": "Décrivez l’installation",
  "o1": "Classification électrique",
  "o2": "Éolien offshore",
  "o3": "Inspection photovoltaïque",
  "o4": "Autre demande",
  "f6": "J’accepte qu’Energy Experts BV conserve et utilise ces informations pour répondre à ma demande, comme décrit dans la politique de confidentialité.",
  "f7": "Envoyer la demande",
  "f8": "Formulaire de démonstration — rien n’est envoyé",
  "sent": "Merci — sur un site en ligne, ce message serait maintenant dans votre boîte de réception.",
  "errName": "Merci d’indiquer votre nom.",
  "errMail": "Merci de vérifier l’adresse e-mail.",
  "errMsg": "Merci de décrire l’installation.",
  "errConsent": "Merci de cocher la case de consentement.",
  "mapH": "Où nous trouver",
  "mapP": "Notre bureau à Grimbergen, juste au nord de Bruxelles.",
  "mapB": "Ouvrir dans Maps",
  "fEnt": "N° d’entreprise",
  "fVat": "TVA",
  "fNav": "Plan du site",
  "fComp": "Société",
  "fFaq": "FAQ",
  "fCareer": "Carrières",
  "fLegal": "Mentions légales",
  "fl1": "Politique de confidentialité",
  "fl3": "Conditions générales",
  "fl4": "Réclamations",
  "fCk": "Paramètres des cookies",
  "fBtm": "Concept graphique · contenu provisoire",
  "ckH": "Nous restons simples",
  "ckP": "Ce site ne dépose aucun cookie et ne charge rien provenant d’autres sociétés. Nous souhaitons uniquement mémoriser votre langue et votre choix clair ou sombre dans ce navigateur. Consultez la <a href=\"#\">politique de confidentialité</a>.",
  "ckAll": "Tout accepter",
  "ckNone": "Tout refuser",
  "ckCust": "Choisir ce qui se charge",
  "pfH": "Ce qui se charge sur ce site",
  "pfP": "Rien dans les deuxième et troisième groupes ne se charge tant que vous ne l’activez pas. Vous pouvez modifier ce choix à tout moment depuis le pied de page.",
  "pf1h": "Strictement nécessaire",
  "pf1p": "Rien. Ce site n’a besoin d’aucun cookie pour fonctionner.",
  "pf2h": "Mémoriser la langue et le thème",
  "pf2p": "Conserve votre langue et votre choix clair ou sombre dans ce navigateur. Jamais partagé.",
  "pf3h": "Statistiques",
  "pf3p": "Comptage anonyme des visites pour savoir quelles pages sont lues. Sans cookie ni donnée personnelle.",
  "pfSave": "Enregistrer",
  "pfAll": "Tout accepter",
  "mDur": "Durée",
  "mScope": "Prestations réalisées",
  "h1v2a": "Un regard indépendant sur",
  "h1v2b": "chaque mégawatt.",
  "h1v3": "Le rapport que votre organisme agréé accepte du premier coup.",
  "h1v4a": "Vérifié en mer.",
  "h1v4b": "Certifié à terre.",
  "ledeShort": "Conception, classification et inspection électriques indépendantes. Belgique, France, Espagne.",
  "tagline": "Inspection électrique indépendante · Belgique",
  "since": "Depuis 2016",
  "locBadge": "Grimbergen · Belgique",
  "whH": "Pourquoi Energy Experts",
  "whSub": "Trois choses sur lesquelles nous ne transigeons pas.",
  "wh1h": "Indépendants par conception",
  "wh1p": "Nous n’installons rien et ne vendons rien. Notre seul produit, c’est le constat.",
  "wh2h": "Signé par l’ingénieur",
  "wh2p": "L’ingénieur sur site est celui qui signe. Pas de relais, pas de juniors.",
  "wh3h": "Quatre langues, une norme",
  "wh3p": "Des rapports dans la langue de votre organisme agréé — NL, FR, EN ou ES.",
  "nwH": "Regards",
  "nwSub": "Notes de terrain.",
  "nwAll": "Tous les articles",
  "readMore": "Lire",
  "nw1t": "Pourquoi les câbles 66 kV cèdent au raccordement",
  "nw1d": "Lire la courbe tan delta avant qu’elle ne devienne une réclamation en garantie.",
  "nw1m": "Offshore · 6 min",
  "nw2t": "RGIE 2025 : ce qui change pour les cabines HT",
  "nw2d": "Les nouvelles règles de classification des zones, expliquées aux responsables de site.",
  "nw2m": "Réglementation · 4 min",
  "nw3t": "La thermographie n’est pas une inspection",
  "nw3d": "Un point chaud est un symptôme. La courbe I-V en donne la cause.",
  "nw3m": "Solaire · 5 min",
  "crH": "Rejoindre le bureau",
  "crP": "Nous recherchons un ingénieur électricien agréé avec expérience en mise en service HT, basé en Belgique et à l’aise en néerlandais et en français.",
  "crB": "Voir les postes ouverts",
  "ctaH": "Une installation en attente de réception ?",
  "ctaP": "Envoyez-nous le schéma unifilaire. Sous deux jours ouvrables, nous vous dirons ce qu’il faut pour la faire valider.",
  "ctaBtn": "Lancer une demande",
  "ctaSmall": "Nous contacter",
  "certH": "Accréditations",
  "cert1": "Partenaire d’inspection reconnu BelAC",
  "cert2": "Certifié sécurité VCA / LSC",
  "cert3": "Management de la qualité ISO 9001",
  "cert4": "GWO Basic Safety Training, offshore",
  "cap1": "Parc éolien offshore Norther, mer du Nord belge",
  "cap2": "Parc éolien de Thorntonbank, vue aérienne",
  "cap3": "Navire câblier, C-Power",
  "cap4": "Centrale PV au sol",
  "cap5": "Appareillage 150 kV",
  "cap6": "Installation d’éoliennes offshore",
  "viewAll": "Tous les projets",
  "scrollHint": "Défiler",
  "learn": "En savoir plus",
  "photoCredits": "Crédits photo",
  "k5": "Rapports remis",
  "mClose": "Fermer",
  "designLabel": "Design",
  "abH3": "À propos d’Energy Experts",
  "msH": "Notre mission",
  "msP": "Rendre chaque installation que nous touchons plus sûre, plus simple à certifier et moins coûteuse à assurer — en plaçant un ingénieur indépendant entre l’entrepreneur et la réception.",
  "ptH": "Ils nous font confiance",
  "ptSub": "Développeurs, gestionnaires de réseau et entreprises EPC au Benelux et en France.",
  "certBtn": "Nos certifications",
  "moreInfo": "Plus d’informations",
  "getInTouch": "Contactez-nous",
  "polH": "Nos engagements en matière de responsabilité et d’intégrité",
  "polSub": "Trois documents que chaque client, partenaire et collaborateur peut nous opposer.",
  "pol1h": "Politique HSE",
  "pol1s": "Santé, sécurité et environnement",
  "pol1p": "Comment nous planifions, travaillons et rendons compte sur site pour que personne ne soit blessé et que rien ne soit déversé.",
  "pol2h": "Politique des droits humains",
  "pol2s": "Travail et chaîne d’approvisionnement",
  "pol2p": "Nos engagements sur le travail, l’égalité de traitement et la chaîne d’approvisionnement, alignés sur les Principes directeurs de l’ONU.",
  "pol3h": "Code de conduite",
  "pol3s": "Indépendance et anticorruption",
  "pol3p": "Règles d’indépendance, de confidentialité et de lutte contre la corruption que chaque ingénieur signe dès son premier jour.",
  "polDl": "Télécharger le PDF",
  "cr1h": "Un travail de pionnier",
  "cr1p": "Réseaux 66 kV, fondations flottantes, hybrides PV-stockage : les installations que vous inspecterez ne figurent encore dans aucun manuel.",
  "cr2h": "Un environnement international",
  "cr2p": "La mer du Nord belge une semaine, une centrale solaire en Aragon la suivante. Quatre langues de travail au bureau.",
  "cr3h": "Évolution et développement",
  "cr3p": "GWO, habilitation aux manœuvres HT et statut d’ingénieur agréé — financés et planifiés dès votre première année.",
  "vacancies": "Postes ouverts",
  "fFirst": "Prénom",
  "fLast": "Nom",
  "fCountry": "Indicatif",
  "fPhone": "Téléphone",
  "prjRef": "Références",
  "tbHint": "Touchez une pale pour ouvrir un projet",
  "tbNext": "Projet suivant",
  "tbPrev": "Précédent",
  "tbOpen": "Ouvrir le dossier",
  "tbAuto": "Tourne automatiquement · survolez ou touchez pour mettre en pause",
  "prjMore": "En savoir plus sur nos projets.",
  "cta2H": "Prêt pour votre prochain projet ?",
  "cta2P": "Un appel suffit pour cadrer le périmètre. Nous vous dirons honnêtement si vous avez besoin de nous.",
  "locH": "Où nous trouver",
  "fSocial": "Suivez-nous",
  "ptDev": "Développeur",
  "ptDev2": "Développeur",
  "ptDev3": "Développeur",
  "ptGrid": "Gestionnaire de réseau",
  "ptMarine": "Entreprise maritime",
  "ptEpc": "EPC offshore",
  "ptUtil": "Énergéticien",
  "ptUtil2": "Énergéticien",
  "ptNote": "Noms fictifs — remplacés par vos vrais clients dès qu’ils acceptent d’être cités."
 },
 "nl": {
  "skip": "Naar inhoud",
  "brandSub": "Besloten Vennootschap",
  "nav1": "Diensten",
  "nav6": "Sectoren",
  "nav2": "Projecten",
  "nav3": "Aanpak",
  "nav4": "Over ons",
  "nav5": "Contact",
  "heroEyebrow": "Onafhankelijke energie-engineering · België",
  "heroH1a": "Elke installatie,",
  "heroH1b": "geverifieerd.",
  "heroLede": "Energy Experts BV levert onafhankelijk elektrisch ontwerp, keuring en inspectie voor offshore wind, zonne-energie en industriële installaties in België, Frankrijk en Nederland.",
  "ctaA": "Vraag een keuring aan",
  "ctaB": "Bekijk ons werk",
  "plateHd": "Bedrijfsgegevens",
  "plateLive": "Actief",
  "pk1": "Opgericht",
  "pk2": "Gevestigd",
  "pk3": "Normen",
  "pk4": "Disciplines",
  "pv4": "Wind · Zon · HS/LS",
  "pk5": "Werkgebied",
  "pk6": "Reactietijd",
  "pv6": "2 werkdagen",
  "stripLbl": "Wij werken volgens",
  "svcEyebrow": "Diensten",
  "svcH2": "Drie disciplines, één dossier",
  "svcSub": "Elke opdracht eindigt in een conformiteitsdossier dat uw keuringsorganisme en uw verzekeraar aanvaarden.",
  "s1h": "Elektrisch ontwerp & keuring",
  "s1p": "Ontwerpbeoordeling, conformiteitsbeoordeling en zoneclassificatie van LS- en HS-installaties volgens het AREI.",
  "s1a": "Nazicht van eendraadschema's",
  "s1b": "Studie van selectiviteit en beveiliging",
  "s1c": "Opmaak van het technisch dossier",
  "s2h": "Offshore wind",
  "s2p": "Ondersteuning bij indienststelling, elektrische inspectie en QA/QC-toezicht voor turbines, parkkabels en offshore hoogspanningsposten.",
  "s2a": "Toezicht op kabelmoffen",
  "s2b": "Ondersteuning HS-indienststelling",
  "s2c": "Afwerking van de restpuntenlijst",
  "s3h": "Inspectie van zonne-installaties",
  "s3p": "Thermografisch onderzoek, string- en isolatiemetingen en IEC 62446-opleveringsrapporten voor daken en grondgebonden parken.",
  "s3a": "Thermografie met drone en handcamera",
  "s3b": "Opmeten van I-V-curves per string",
  "s3c": "Analyse van tegenvallende opbrengst",
  "secEyebrow": "Sectoren",
  "secH2": "Waar wij werken",
  "secSub": "Vier omgevingen, elk met een eigen reglement en eigen faalmechanismen.",
  "x1h": "Offshore & maritiem",
  "x1p": "Windparken, exportkabels en offshore posten in de Belgische en Nederlandse Noordzee.",
  "x2h": "Grootschalige zonne-energie",
  "x2p": "Grondgebonden parken vanaf 1 MWp in Frankrijk, Nederland en de Benelux.",
  "x3h": "Industrie & logistiek",
  "x3p": "Verdeelborden, transformatorlokalen en HS-cabines in fabrieken en magazijnen.",
  "x4h": "Net & hoogspanningsposten",
  "x4p": "Aansluitstudies en conformiteitskeuring tot 150 kV.",
  "prjEyebrow": "Projectregister",
  "prjH2": "Recente opdrachten",
  "prjSub": "Klik op een rij voor de volledige opdracht en de technische samenvatting.",
  "th1": "Project",
  "th2": "Locatie",
  "th3": "Vermogen",
  "th4": "Opdracht",
  "th5": "Jaar",
  "regNote": "Voorbeelden — u voegt deze zelf toe, past ze aan en verwijdert ze, zonder ontwikkelaar.",
  "appEyebrow": "Werkwijze",
  "appH2": "Hoe een opdracht verloopt",
  "appSub": "Vier fasen, van het eerste schema tot een goedgekeurde installatie.",
  "n1": "Fase 01",
  "a1h": "Intake",
  "a1p": "Wij verzamelen eendraadschema's, beveiligingsinstellingen en as-builtdocumentatie voordat er iemand ter plaatse gaat.",
  "n2": "Fase 02",
  "a2h": "Metingen ter plaatse",
  "a2p": "Op locatie: isolatieweerstand, aardingscontinuïteit, thermografie en controle van aanhaalmomenten.",
  "n3": "Fase 03",
  "a3h": "Conformiteitsdossier",
  "a3p": "De vaststellingen worden gebundeld in een rapport dat uw keuringsorganisme in één keer aanvaardt.",
  "n4": "Fase 04",
  "a4h": "Goedkeuring",
  "a4p": "Advies over herstelmaatregelen en herkeuring tot de installatie is goedgekeurd.",
  "abEyebrow": "Over ons",
  "abH2": "Ingenieurs, geen auditors.",
  "abP1": "Wij zijn een klein Belgisch bureau van erkende elektrotechnisch ingenieurs, actief in windenergie op de Noordzee, industriële energie en grootschalige zonne-energie. Elke opdracht wordt uitgevoerd door de ingenieur die het rapport ondertekent.",
  "abP2": "Onafhankelijkheid is het product. Wij hebben geen banden met leveranciers en installeren niets, dus onze vaststellingen zijn alleen verantwoording schuldig aan de norm en aan u.",
  "k1": "Uitgevoerde keuringen",
  "k2": "Beoordeeld vermogen",
  "k3": "Landen",
  "k4": "Jaar actief",
  "r1": "Zaakvoerder",
  "b1": "Erkend elektrotechnisch ingenieur. Twintig jaar HS-indienststelling op de Noordzee.",
  "r2": "Hoofd inspectie",
  "b2": "Leidt het AREI-conformiteitswerk en ondertekent de technische dossiers.",
  "r3": "Verantwoordelijke zonne-energie",
  "b3": "IEC 62446-indienststelling en thermografisch onderzoek in Frankrijk en Nederland.",
  "qT": "Ze vonden een fout in een beveiligingsinstelling die twee andere partijen al hadden afgetekend. Het rapport werd zonder één enkele opmerking aanvaard door ons keuringsorganisme.",
  "qN": "Projectdirecteur",
  "qC": "ontwikkelaar offshore wind, Oostende",
  "faqEyebrow": "Vragen",
  "faqH2": "Voordat u belt",
  "q1": "Hoe snel kunt u ter plaatse zijn?",
  "an1": "Voor installaties in België doorgaans binnen vijf werkdagen. Offshore opdrachten worden ingepland rond het vaarvenster en op voorhand afgesproken.",
  "q2": "Levert u het officiële keuringsverslag?",
  "an2": "Nee, en dat is bewust. Wij stellen het conformiteitsdossier op en corrigeren de vaststellingen, zodat het erkende keuringsorganisme zonder bezwaar kan keuren. Die rollen gescheiden houden is precies wat het dossier geloofwaardig maakt.",
  "q3": "In welke talen rapporteert u?",
  "an3": "Nederlands, Frans, Engels en Spaans. Het rapport wordt geleverd in de werktaal van uw keuringsorganisme.",
  "q4": "Werkt u ook buiten België?",
  "an4": "Regelmatig. Ongeveer de helft van ons werk in zonne-energie ligt in Frankrijk en Nederland, en de offshore opdrachten beslaan de Belgische en Nederlandse Noordzee.",
  "ctEyebrow": "Contact",
  "ctH2": "Vertel ons over de installatie.",
  "ctP": "Stuur de basisgegevens door en wij komen binnen twee werkdagen terug met een opdrachtomschrijving en een prijs.",
  "c1": "Kantoor",
  "c2": "Telefoon",
  "c3": "E-mail",
  "c4": "Openingsuren",
  "c4v": "Ma–vr, 08:00–17:00 CET",
  "f1": "Naam",
  "f2": "Bedrijf",
  "f3": "E-mail",
  "f4": "Dienst",
  "o1": "Elektrische keuring",
  "o2": "Offshore wind",
  "o3": "Inspectie zonne-installatie",
  "o4": "Iets anders",
  "f5": "Beschrijf de installatie",
  "f6": "Ik ga ermee akkoord dat Energy Experts BV deze gegevens bewaart en gebruikt om mijn vraag te beantwoorden, zoals beschreven in de privacyverklaring.",
  "f7": "Vraag versturen",
  "f8": "Demoformulier — er wordt niets verzonden",
  "mapH": "Kaart",
  "mapP": "Ons kantoor in Grimbergen, ten noorden van Brussel.",
  "mapB": "Openen in Maps",
  "brandSub2": "Besloten Vennootschap",
  "fEnt": "Ondernemingsnr.",
  "fVat": "btw",
  "fNav": "Site",
  "nav1b": "Diensten",
  "nav6b": "Sectoren",
  "nav2b": "Projecten",
  "nav3b": "Aanpak",
  "fComp": "Bedrijf",
  "nav4b": "Over ons",
  "fFaq": "Veelgestelde vragen",
  "nav5b": "Contact",
  "fCareer": "Vacatures",
  "fLegal": "Juridisch",
  "fl1": "Privacyverklaring",
  "fl3": "Algemene voorwaarden",
  "fl4": "Klachten",
  "fCk": "Voorkeuren",
  "fBtm": "Ontwerpconcept · voorbeeldinhoud",
  "ckH": "Wij houden het eenvoudig",
  "ckP": "Deze site plaatst geen cookies en laadt niets van andere bedrijven. Wij willen enkel uw taal en uw keuze voor licht of donker in deze browser onthouden. Lees de <a href=\"#\">privacyverklaring</a>.",
  "ckAll": "Mijn keuzes onthouden",
  "ckNone": "Niets bewaren",
  "ckCust": "Zelf kiezen",
  "pfH": "Wat deze site bewaart",
  "pfP": "Er wordt niets in uw browser bewaard tot u dat hieronder toestaat. U kunt dit altijd wijzigen via de voettekst.",
  "pf1h": "Strikt noodzakelijk",
  "pf1p": "Niets. Deze site heeft geen cookie nodig om te werken.",
  "pf2h": "Taal en thema onthouden",
  "pf2p": "Bewaart uw taalkeuze en licht of donker in deze browser. Wordt nooit gedeeld.",
  "pf3h": "Statistieken",
  "pf3p": "Anoniem bezoekersaantal zodat we weten welke pagina's gelezen worden. Geen cookie, geen persoonsgegevens.",
  "pfSave": "Keuzes bewaren",
  "pfAll": "Alles toestaan",
  "mDur": "Doorlooptijd",
  "mScope": "Geleverde opdracht",
  "sent": "Bedankt — op een live site zou dit nu in uw mailbox staan.",
  "errName": "Vul uw naam in.",
  "errMail": "Controleer het e-mailadres.",
  "errMsg": "Beschrijf de installatie.",
  "errConsent": "Vink het toestemmingsvakje aan.",
  "h1v2a": "Onafhankelijke ogen op",
  "h1v2b": "elke megawatt.",
  "h1v3": "Het rapport dat uw keuringsorganisme in één keer aanvaardt.",
  "h1v4a": "Geverifieerd op zee.",
  "h1v4b": "Gekeurd aan wal.",
  "ledeShort": "Onafhankelijk elektrisch ontwerp, keuring en inspectie. België, Frankrijk, Nederland.",
  "tagline": "Onafhankelijke elektrische keuring · België",
  "since": "Sinds 2016",
  "locBadge": "Grimbergen · België",
  "whH": "Waarom Energy Experts",
  "whSub": "Drie zaken waarop wij niet toegeven.",
  "wh1h": "Onafhankelijk van opzet",
  "wh1p": "Wij installeren niets en verkopen niets. Ons enige product is de vaststelling.",
  "wh2h": "Ondertekend door de ingenieur",
  "wh2p": "De ingenieur op de werf is de ingenieur die tekent. Geen doorgeefluik, geen juniors.",
  "wh3h": "Vier talen, één norm",
  "wh3p": "Rapporten in de taal van uw keuringsorganisme — NL, FR, EN of ES.",
  "nwH": "Inzichten",
  "nwSub": "Notities van het terrein.",
  "nwAll": "Alle artikelen",
  "readMore": "Lezen",
  "nw1t": "Waarom 66 kV-parkkabels falen bij de mof",
  "nw1d": "De tan delta-curve lezen voordat het een garantiedossier wordt.",
  "nw1m": "Offshore · 6 min",
  "nw2t": "AREI 2025: wat verandert er voor HS-cabines",
  "nw2d": "De herziene regels voor zoneclassificatie, uitgelegd voor werfleiders.",
  "nw2m": "Regelgeving · 4 min",
  "nw3t": "Thermografie is geen inspectie",
  "nw3d": "Een warm punt is een symptoom. De I-V-curve geeft de oorzaak.",
  "nw3m": "Zonne-energie · 5 min",
  "crH": "Kom bij ons werken",
  "crP": "Wij zoeken een erkend elektrotechnisch ingenieur met ervaring in HS-indienststelling, gevestigd in België en vlot in het Nederlands en het Frans.",
  "crB": "Bekijk de vacatures",
  "ctaH": "Wacht een installatie op goedkeuring?",
  "ctaP": "Stuur ons het eendraadschema. Binnen twee werkdagen zeggen wij wat er nodig is om ze goedgekeurd te krijgen.",
  "ctaBtn": "Start een aanvraag",
  "ctaSmall": "Neem contact op",
  "certH": "Erkenningen",
  "cert1": "Erkend inspectiepartner (BELAC)",
  "cert2": "VCA / LSC-veiligheidscertificaat",
  "cert3": "ISO 9001-kwaliteitsbeheer",
  "cert4": "GWO Basic Safety Training, offshore",
  "cap1": "Windpark Norther, Belgische Noordzee",
  "cap2": "Windpark Thorntonbank, luchtbeeld",
  "cap3": "Kabellegschip, C-Power",
  "cap4": "Grondgebonden PV-park",
  "cap5": "Schakelinstallatie 150 kV",
  "cap6": "Installatie van offshore windturbines",
  "viewAll": "Alle projecten",
  "scrollHint": "Scrollen",
  "learn": "Meer weten",
  "photoCredits": "Fotoverantwoording",
  "k5": "Uitgebrachte rapporten",
  "mClose": "Sluiten",
  "designLabel": "Ontwerp",
  "abH3": "Over Energy Experts",
  "msH": "Onze missie",
  "msP": "Elke installatie die wij behandelen veiliger, eenvoudiger te keuren en goedkoper te verzekeren maken — door een onafhankelijke ingenieur tussen de aannemer en de goedkeuring te plaatsen.",
  "ptH": "Partners die ons vertrouwen",
  "ptSub": "Ontwikkelaars, netbeheerders en EPC-aannemers in de Benelux en Frankrijk.",
  "certBtn": "Onze erkenningen",
  "moreInfo": "Meer informatie",
  "getInTouch": "Neem contact op",
  "polH": "Onze richtlijnen voor verantwoordelijkheid en integriteit",
  "polSub": "Drie documenten waarop elke klant, partner en medewerker ons mag aanspreken.",
  "pol1h": "VGM-beleid",
  "pol1s": "Veiligheid, gezondheid & milieu",
  "pol1p": "Hoe wij plannen, werken en rapporteren op de werf zodat niemand gewond raakt en er niets wordt gemorst.",
  "pol2h": "Mensenrechtenbeleid",
  "pol2s": "Arbeid & toeleveringsketen",
  "pol2p": "Onze engagementen rond arbeid, gelijke behandeling en de toeleveringsketen, afgestemd op de VN-richtlijnen.",
  "pol3h": "Gedragscode",
  "pol3s": "Onafhankelijkheid & anticorruptie",
  "pol3p": "Regels rond onafhankelijkheid, vertrouwelijkheid en anticorruptie die elke ingenieur op dag één ondertekent.",
  "polDl": "Pdf downloaden",
  "cr1h": "Pionierswerk",
  "cr1p": "66 kV-parken, drijvende funderingen, hybride PV met opslag: de installaties die u keurt staan nog in geen enkel handboek.",
  "cr2h": "Internationale omgeving",
  "cr2p": "De ene week de Belgische Noordzee, de volgende een zonnepark in Frankrijk. Vier werktalen op kantoor.",
  "cr3h": "Groei en ontwikkeling",
  "cr3p": "GWO, HS-schakelbevoegdheid en erkenning als ingenieur — betaald en ingepland vanaf uw eerste jaar.",
  "vacancies": "Vacatures",
  "fFirst": "Voornaam",
  "fLast": "Achternaam",
  "fCountry": "Landcode",
  "fPhone": "Telefoonnummer",
  "prjRef": "Projectreferenties",
  "tbHint": "Tik op een blad om een project te openen",
  "tbNext": "Volgend project",
  "tbPrev": "Vorige",
  "tbOpen": "Dossier openen",
  "tbAuto": "Draait vanzelf · beweeg of tik om te pauzeren",
  "prjMore": "Ontdek meer over onze projecten.",
  "cta2H": "Klaar voor uw volgende project?",
  "cta2P": "Eén gesprek volstaat om de opdracht af te bakenen. Wij zeggen u eerlijk of u ons nodig hebt.",
  "locH": "Waar u ons vindt",
  "fSocial": "Volg ons",
  "ptDev": "Ontwikkelaar",
  "ptDev2": "Ontwikkelaar",
  "ptDev3": "Ontwikkelaar",
  "ptGrid": "Netbeheerder",
  "ptMarine": "Maritiem aannemer",
  "ptEpc": "Offshore EPC",
  "ptUtil": "Energiebedrijf",
  "ptUtil2": "Energiebedrijf",
  "ptNote": "Fictieve namen — vervangen door uw echte klanten zodra zij akkoord gaan om vermeld te worden."
 }
};
