/* GENERATED by build.py from content/ -- do not edit by hand. */
var PROJECTS = [
 {
  "name": "Norther OWF",
  "cap": "370 MW",
  "year": "2024",
  "dur": "14 mo",
  "img": "img/wind-norther.jpg",
  "tag": {
   "en": "Offshore wind",
   "fr": "Éolien offshore",
   "nl": "Offshore wind"
  },
  "loc": {
   "en": "Belgian North Sea",
   "fr": "Mer du Nord belge",
   "nl": "Belgische Noordzee"
  },
  "scope": {
   "en": "Array cable QA/QC",
   "fr": "QA/QC câbles inter-éoliennes",
   "nl": "QA/QC parkkabels"
  },
  "desc": {
   "en": "Witness and documentation of 66 kV array cable terminations across 44 turbine positions, including pull-in supervision and post-installation testing.",
   "fr": "Témoin et documentation des raccordements de câbles 66 kV sur 44 positions d’éoliennes, avec supervision du tirage et essais après installation.",
   "nl": "Toezicht op en documentatie van 66 kV-kabelmoffen op 44 turbineposities, inclusief begeleiding van het intrekken en beproeving na installatie."
  },
  "list": {
   "en": [
    "Termination witness, 44 positions",
    "VLF and tan delta testing",
    "Punch list close-out with the EPC"
   ],
   "fr": [
    "Témoin de raccordement, 44 positions",
    "Essais VLF et tan delta",
    "Clôture des réserves avec l’EPC"
   ],
   "nl": [
    "Toezicht op moffen, 44 posities",
    "VLF- en tan delta-metingen",
    "Afwerking restpunten met de EPC"
   ]
  }
 },
 {
  "name": "Rentel OWF",
  "cap": "309 MW",
  "year": "2023",
  "dur": "9 mo",
  "img": "img/oss-blighbank.jpg",
  "tag": {
   "en": "Offshore wind",
   "fr": "Éolien offshore",
   "nl": "Offshore wind"
  },
  "loc": {
   "en": "Belgian North Sea",
   "fr": "Mer du Nord belge",
   "nl": "Belgische Noordzee"
  },
  "scope": {
   "en": "Commissioning support",
   "fr": "Assistance mise en service",
   "nl": "Ondersteuning indienststelling"
  },
  "desc": {
   "en": "HV commissioning support on the offshore substation, covering protection settings verification, earthing survey and energisation readiness.",
   "fr": "Assistance à la mise en service HT du poste offshore : vérification des réglages de protection, relevé des terres et revue de mise sous tension.",
   "nl": "Ondersteuning bij de HS-indienststelling van de offshore post: controle van beveiligingsinstellingen, aardingsonderzoek en gereedheid voor inschakeling."
  },
  "list": {
   "en": [
    "Protection settings verification",
    "Earthing and bonding survey",
    "Energisation readiness review"
   ],
   "fr": [
    "Vérification des réglages de protection",
    "Relevé des terres et liaisons",
    "Revue de mise sous tension"
   ],
   "nl": [
    "Controle van beveiligingsinstellingen",
    "Onderzoek aarding en vereffening",
    "Nazicht gereedheid voor inschakeling"
   ]
  }
 },
 {
  "name": "Kortrijk Logistics Hub",
  "cap": "4.2 MWp",
  "year": "2024",
  "dur": "3 wk",
  "img": "img/solar-nottuln.jpg",
  "tag": {
   "en": "Solar PV",
   "fr": "Photovoltaïque",
   "nl": "Zonne-energie"
  },
  "loc": {
   "en": "Kortrijk, BE",
   "fr": "Courtrai, BE",
   "nl": "Kortrijk, BE"
  },
  "scope": {
   "en": "PV thermographic survey",
   "fr": "Thermographie PV",
   "nl": "Thermografie PV"
  },
  "desc": {
   "en": "Full-array drone thermography over 9,800 modules after a first-year yield shortfall, with string-level I-V tracing on every flagged section.",
   "fr": "Thermographie par drone sur 9 800 modules après un déficit de production la première année, avec relevé de courbes I-V sur chaque zone signalée.",
   "nl": "Thermografie met drone over 9.800 panelen na een tegenvallende opbrengst in het eerste jaar, met I-V-metingen op elke gemarkeerde zone."
  },
  "list": {
   "en": [
    "Drone thermography, 9,800 modules",
    "I-V curve tracing on flagged strings",
    "Warranty claim documentation"
   ],
   "fr": [
    "Thermographie drone, 9 800 modules",
    "Courbes I-V sur les chaînes signalées",
    "Dossier de réclamation en garantie"
   ],
   "nl": [
    "Dronethermografie, 9.800 panelen",
    "I-V-curves op gemarkeerde strings",
    "Dossier voor garantieclaim"
   ]
  }
 },
 {
  "name": "Zeebrugge Substation",
  "cap": "150 kV",
  "year": "2023",
  "dur": "6 wk",
  "img": "img/hv-switchgear-1.jpg",
  "tag": {
   "en": "Grid",
   "fr": "Réseau",
   "nl": "Net"
  },
  "loc": {
   "en": "Zeebrugge, BE",
   "fr": "Zeebruges, BE",
   "nl": "Zeebrugge, BE"
  },
  "scope": {
   "en": "Conformity classification",
   "fr": "Classification de conformité",
   "nl": "Conformiteitskeuring"
  },
  "desc": {
   "en": "AREI/RGIE conformity classification of a 150 kV connection cabin, preparing the technical dossier for the accredited inspection body.",
   "fr": "Classification de conformité RGIE d’une cabine de raccordement 150 kV, avec constitution du dossier technique pour l’organisme agréé.",
   "nl": "AREI-conformiteitskeuring van een aansluitcabine van 150 kV, met opmaak van het technisch dossier voor het erkende keuringsorganisme."
  },
  "list": {
   "en": [
    "Zone classification to AREI/RGIE",
    "Single-line diagram reconstruction",
    "Dossier accepted first submission"
   ],
   "fr": [
    "Classification des zones selon le RGIE",
    "Reconstitution du schéma unifilaire",
    "Dossier accepté au premier dépôt"
   ],
   "nl": [
    "Zoneclassificatie volgens AREI",
    "Reconstructie van het eendraadschema",
    "Dossier in één keer aanvaard"
   ]
  }
 },
 {
  "name": "Parc Solaire Occitanie",
  "cap": "12 MWp",
  "year": "2025",
  "dur": "5 wk",
  "img": "img/solar-dulmen.jpg",
  "tag": {
   "en": "Solar PV",
   "fr": "Photovoltaïque",
   "nl": "Zonne-energie"
  },
  "loc": {
   "en": "Toulouse, FR",
   "fr": "Toulouse, FR",
   "nl": "Toulouse, FR"
  },
  "scope": {
   "en": "IEC 62446 commissioning",
   "fr": "Mise en service IEC 62446",
   "nl": "Indienststelling IEC 62446"
  },
  "desc": {
   "en": "Full IEC 62446-1 commissioning campaign on a ground-mount park, delivered in French for the client's contrôleur technique.",
   "fr": "Campagne complète de mise en service IEC 62446-1 sur une centrale au sol, remise en français pour le contrôleur technique du client.",
   "nl": "Volledige indienststellingscampagne volgens IEC 62446-1 op een grondgebonden park, opgeleverd in het Frans voor de contrôleur technique van de klant."
  },
  "list": {
   "en": [
    "Insulation and continuity testing",
    "Inverter parameter verification",
    "Commissioning report in French"
   ],
   "fr": [
    "Essais d’isolement et de continuité",
    "Vérification des paramètres onduleurs",
    "Rapport de mise en service en français"
   ],
   "nl": [
    "Isolatie- en continuïteitsmetingen",
    "Controle van omvormerparameters",
    "Opleveringsrapport in het Frans"
   ]
  }
 },
 {
  "name": "Zonnepark Flevoland",
  "cap": "28 MWp",
  "year": "2025",
  "dur": "11 mo",
  "img": "img/wind-thornton-air.jpg",
  "tag": {
   "en": "Solar PV",
   "fr": "Photovoltaïque",
   "nl": "Zonne-energie"
  },
  "loc": {
   "en": "Flevoland, NL",
   "fr": "Flevoland, NL",
   "nl": "Flevoland, NL"
  },
  "scope": {
   "en": "Owner's engineer",
   "fr": "Ingénieur du maître d’ouvrage",
   "nl": "Ingenieur van de bouwheer"
  },
  "desc": {
   "en": "Owner's engineer through construction and handover, from design review to provisional acceptance, reporting in Dutch and English.",
   "fr": "Ingénieur du maître d’ouvrage pendant la construction et la réception, de la revue de conception à la réception provisoire, en néerlandais et en anglais.",
   "nl": "Ingenieur van de bouwheer tijdens bouw en oplevering, van ontwerpnazicht tot voorlopige oplevering, met rapportering in het Nederlands en het Engels."
  },
  "list": {
   "en": [
    "Design review and approvals",
    "Monthly site surveillance",
    "Provisional acceptance punch list"
   ],
   "fr": [
    "Revue de conception et validations",
    "Surveillance mensuelle du chantier",
    "Réserves de réception provisoire"
   ],
   "nl": [
    "Ontwerpnazicht en goedkeuringen",
    "Maandelijks werftoezicht",
    "Restpuntenlijst voorlopige oplevering"
   ]
  }
 }
];
var NEWS = [
 {
  "date": "2026-08-19",
  "read": "6",
  "img": "img/vessel-cable.jpg",
  "cat": {
   "en": "Offshore",
   "fr": "Offshore",
   "nl": "Offshore"
  },
  "title": {
   "en": "Why 66 kV array cables fail at the termination",
   "fr": "Pourquoi les câbles 66 kV cèdent au raccordement",
   "nl": "Waarom 66 kV-parkkabels falen bij de mof"
  },
  "excerpt": {
   "en": "Reading the tan delta curve before it becomes a warranty claim.",
   "fr": "Lire la courbe tan delta avant qu’elle ne devienne une réclamation en garantie.",
   "nl": "De tan delta-curve lezen voordat het een garantiedossier wordt."
  }
 },
 {
  "date": "2026-07-02",
  "read": "4",
  "img": "img/hv-switchgear-1.jpg",
  "cat": {
   "en": "Regulation",
   "fr": "Réglementation",
   "nl": "Regelgeving"
  },
  "title": {
   "en": "AREI/RGIE 2025: what changed for HV cabins",
   "fr": "RGIE 2025 : ce qui change pour les cabines HT",
   "nl": "AREI 2025: wat verandert er voor HS-cabines"
  },
  "excerpt": {
   "en": "The revised zone classification rules, explained for site managers.",
   "fr": "Les nouvelles règles de classification des zones, expliquées aux responsables de site.",
   "nl": "De herziene regels voor zoneclassificatie, uitgelegd voor werfleiders."
  }
 },
 {
  "date": "2026-05-28",
  "read": "5",
  "img": "img/solar-nottuln.jpg",
  "cat": {
   "en": "Solar",
   "fr": "Solaire",
   "nl": "Zonne-energie"
  },
  "title": {
   "en": "Thermography is not an inspection",
   "fr": "La thermographie n’est pas une inspection",
   "nl": "Thermografie is geen inspectie"
  },
  "excerpt": {
   "en": "A hot spot is a symptom. The I-V trace tells you the cause.",
   "fr": "Un point chaud est un symptôme. La courbe I-V en donne la cause.",
   "nl": "Een warm punt is een symptoom. De I-V-curve geeft de oorzaak."
  }
 }
];
