const HORIZON_COPY = {
  en: {
    skip: 'Skip to content', concept: 'HORIZON / A design concept for Energy Experts BV', conceptNote: 'Sample content · For discussion',
    navLabel: 'Main navigation', mobileNav: 'Mobile navigation', navExpertise: 'Expertise', navProjects: 'Our work', navApproach: 'Our approach', navAbout: 'About us', letsTalk: 'Let’s talk', language: 'Select language', menuOpen: 'Open navigation', menuClose: 'Close navigation', belgiumEurope: 'Based in Belgium. Looking ahead.',
    heroLabel: 'Independent minds. Positive energy.', heroLine1: 'Good energy.', heroLine2: 'Great expertise.', heroText: 'From the first drawing to the final inspection. Clear thinking and practical expertise for a world powered differently.', exploreExpertise: 'Explore our expertise', heroScroll: 'A better future, engineered.', heroLocation: 'NORTH SEA, BELGIUM', heroAlt: 'Wind turbines rising above the Belgian North Sea at Thornton Bank',
    sectorsLabel: 'Our sectors', sectorCaption: 'Three disciplines. One clear purpose.', sectorElectrical: 'Electrical engineering', sectorWind: 'Offshore wind', sectorSolar: 'Solar energy',
    introLabel: 'Progress, with purpose', introTitle1: 'Big ambitions need', introTitle2: 'a steady hand.', introText: 'Energy is changing. We help make that change work — bringing clarity to complex electrical systems, confidence to offshore projects, and care to every solar installation.', meetExperts: 'Get to know us',
    expertiseLabel: '01 / Our expertise', expertiseTitle: 'Technical by nature.\nPractical by design.', expertiseText: 'The right knowledge, exactly where it matters. Explore the disciplines behind our work.',
    electricalTitle: 'Clarity in every\nconnection.', electricalText: 'Thoughtful design and classification for electrical systems that work safely and efficiently.', electricalScope: 'Example scope: design reviews, technical documentation, installation assessments, and practical recommendations. Final services to be confirmed.',
    windTitle: 'Confidence beyond\nthe coastline.', windText: 'Specialist support for the unique demands of wind energy, from planning to operation.', windScope: 'Example scope: project coordination, quality reviews, electrical inspections, and commissioning support. Final services to be confirmed.',
    solarTitle: 'More certainty.\nFrom every ray.', solarText: 'Careful inspection and clear advice to help solar installations deliver on their potential.', solarScope: 'Example scope: visual inspections, performance reviews, documentation checks, and improvement advice. Final services to be confirmed.', serviceScope: 'Explore the scope', discussService: 'Discuss this service ↗',
    projectsLabel: '02 / In the field', projectsTitle1: 'Expertise in action.', projectsTitle2: 'Impact in the making.', projectsText: 'Every project has its own challenges. Here is how your future project stories could look.', sampleProjects: 'Illustrative projects', filterLabel: 'Filter projects', filterAll: 'All projects', filterElectrical: 'Electrical', projectNote: 'A glimpse of what’s possible. These are sample stories, not claims of completed client work.', projectCount: '{count} shown / 03', projectOpen: 'Explore project: ',
    approachLabel: '03 / How we work', approachTitle1: 'Complex projects.', approachTitle2: 'A clear way forward.', approachText: 'Good engineering starts with a good conversation. We keep things clear, collaborative, and focused on your next step.', startConversation: 'Start a conversation',
    step1Label: 'First, we listen', step1Title: 'Understand the ambition.', step1Text: 'Your project, your priorities, your challenges. We start by asking the right questions.', step2Label: 'Then, we get specific', step2Title: 'Make a clear plan.', step2Text: 'An agreed scope, practical milestones, and a shared understanding of what success looks like.', step3Label: 'Together, we move forward', step3Title: 'Deliver with care.', step3Text: 'Hands-on expertise, open communication, and useful answers at every stage of the work.',
    aboutLabel: 'The people behind the progress', aboutTitle1: 'Grounded in expertise.', aboutTitle2: 'Looking to tomorrow.', aboutText: 'Based in Grimbergen, Belgium, Energy Experts BV brings together electrical design, offshore wind, and solar energy services. Our focus is simple: helping you move forward with confidence.', aboutAlt: 'An offshore electrical substation at sea', aboutPhotoLabel: 'Where engineering meets the elements.', value1: 'Clear thinking.', value2: 'Practical solutions.', value3: 'Personal commitment.', meetUs: 'Let’s get acquainted',
    contactLabel: 'Good things start with a conversation', contactTitle1: 'What’s on', contactTitle2: 'your horizon?', contactText: 'An idea, a technical challenge, or a project ready to take its next step. We would love to hear about it.', belgium: 'Belgium',
    formTitle: 'Tell us a little about your project.', formDemo: 'Preview form · No data is sent or saved', formName: 'Your name', formEmail: 'Email address', formService: 'How can we help?', serviceChoose: 'Select a service', serviceOther: 'Let’s explore it together', formMessage: 'A few words about your project', formPrivacy: 'This demonstration stays in your browser.', sendPreview: 'Preview enquiry', namePlaceholder: 'Alex Morgan', emailPlaceholder: 'alex@company.com', messagePlaceholder: 'The ambition, the location, the next step…', formSuccess: 'Your preview is ready. On the live website, this would reach the Energy Experts team. Nothing has been sent or saved.', formInvalid: 'Please complete all fields and write at least 10 characters about your project.',
    closing: 'Better energy starts with better conversations.', footerTagline: 'Independent minds.\nA shared energy for what’s next.', footerConcept: '· Design concept', backTop: 'Back to top', privacyLink: 'Privacy information', cookiesLink: 'Cookies', legalLink: 'Legal notice', creditsLink: 'Photo credits', closeDetails: 'Close details',
    projectScope: 'Example scope', projectDisclaimer: 'Illustrative project only. The location, story, and scope are placeholders. Photography shows real infrastructure and does not imply an Energy Experts assignment.', projectCta: 'Discuss a similar project', sampleLabel: 'Sample project',
    privacyTitle: 'Privacy, kept simple.', privacyText: 'This is a local design preview, not the final company privacy policy. The form performs validation in your browser only. It has no submission endpoint and does not send or save your enquiry.', privacyText2: 'This concept includes no analytics, advertising pixels, embedded maps, or external font requests. Language is kept in the page URL. Your browser and any server used to share this preview may still keep normal history or access logs. Clicking an email or telephone link opens your chosen application.', privacyText3: 'Before launch, the company must approve a policy describing the actual data controller, purposes, lawful bases, retention, recipients, international transfers, and applicable rights, including how to complain to the Belgian Data Protection Authority.',
    cookiesTitle: 'A little less tracking.\nA little more trust.', cookiesText: 'This concept does not set cookies or use local storage. There are no analytics, advertising tools, embedded videos, or third-party maps. All fonts, scripts, and photographs are served with the page.', cookiesText2: 'Your language selection is stored only in the URL. No cookie consent banner is included because this preview has no optional tracking to approve. The final hosting platform must be checked before making this same claim on the live website.', cookiesText3: 'If optional tracking or embeds are introduced later, their consent controls and privacy information must be implemented before they load.',
    legalTitle: 'Company details.', legalText: 'Energy Experts BV\nAlbrecht Rodenbachlaan 29\n1850 Grimbergen, Belgium\ninfo@energyexpertsbv.com\n+32 472 18 42 20', legalText2: 'Design preview only. The company name and contact details are taken from the existing public website and require client confirmation. The registered company name, enterprise number, VAT status and applicable registry details must be supplied before publication.', legalText3: 'All service descriptions are draft copy. All project stories are illustrative. No certifications, customer relationships, track record, or performance figures are asserted by this concept.'
  },
  fr: {
    skip: 'Aller au contenu', concept: 'HORIZON / Un concept pour Energy Experts BV', conceptNote: 'Contenu de démonstration · Pour discussion',
    navLabel: 'Navigation principale', mobileNav: 'Navigation mobile', navExpertise: 'Expertises', navProjects: 'Nos projets', navApproach: 'Notre approche', navAbout: 'À propos', letsTalk: 'Parlons-en', language: 'Choisir la langue', menuOpen: 'Ouvrir la navigation', menuClose: 'Fermer la navigation', belgiumEurope: 'Ancrés en Belgique. Tournés vers l’avenir.',
    heroLabel: 'Un regard indépendant. Une énergie positive.', heroLine1: 'L’énergie juste.', heroLine2: 'L’expertise en plus.', heroText: 'Du premier plan à l’inspection finale. Des idées claires et une expertise concrète pour un monde qui change d’énergie.', exploreExpertise: 'Découvrir nos expertises', heroScroll: 'Concevoir un avenir meilleur.', heroLocation: 'MER DU NORD, BELGIQUE', heroAlt: 'Éoliennes du banc Thornton en mer du Nord, au large de la Belgique',
    sectorsLabel: 'Nos domaines', sectorCaption: 'Trois disciplines. Une même ambition.', sectorElectrical: 'Ingénierie électrique', sectorWind: 'Éolien en mer', sectorSolar: 'Énergie solaire',
    introLabel: 'Un progrès qui a du sens', introTitle1: 'Les grandes ambitions', introTitle2: 'méritent un appui solide.', introText: 'L’énergie évolue. Nous accompagnons ce changement : plus de clarté pour les systèmes électriques complexes, de confiance pour les projets en mer et d’attention pour chaque installation solaire.', meetExperts: 'Faisons connaissance',
    expertiseLabel: '01 / Nos expertises', expertiseTitle: 'La rigueur technique.\nLe sens du concret.', expertiseText: 'Les bonnes compétences, là où elles comptent. Découvrez les disciplines qui animent notre travail.',
    electricalTitle: 'La clarté à chaque\nconnexion.', electricalText: 'Une conception et une classification réfléchies, pour des systèmes électriques sûrs et efficaces.', electricalScope: 'Exemples de prestations : revue de conception, documentation technique, évaluation des installations et recommandations pratiques. Prestations finales à confirmer.',
    windTitle: 'La confiance au-delà\ndu littoral.', windText: 'Un accompagnement spécialisé pour les défis de l’éolien, de la planification à l’exploitation.', windScope: 'Exemples de prestations : coordination de projet, revues qualité, inspections électriques et assistance à la mise en service. Prestations finales à confirmer.',
    solarTitle: 'Plus de confiance.\nDans chaque rayon.', solarText: 'Des inspections soignées et des conseils clairs pour révéler le potentiel des installations solaires.', solarScope: 'Exemples de prestations : inspections visuelles, revues de performance, vérification documentaire et conseils d’amélioration. Prestations finales à confirmer.', serviceScope: 'Découvrir les prestations', discussService: 'Parlons de ce service ↗',
    projectsLabel: '02 / Sur le terrain', projectsTitle1: 'L’expertise en action.', projectsTitle2: 'L’avenir en construction.', projectsText: 'Chaque projet a ses propres défis. Voici comment vos futures réalisations pourraient être présentées.', sampleProjects: 'Projets illustratifs', filterLabel: 'Filtrer les projets', filterAll: 'Tous les projets', filterElectrical: 'Électricité', projectNote: 'Un aperçu des possibles. Ces exemples ne représentent pas des missions réalisées pour des clients.', projectCount: '{count} affiché(s) / 03', projectOpen: 'Découvrir le projet : ',
    approachLabel: '03 / Notre méthode', approachTitle1: 'Des projets complexes.', approachTitle2: 'Une direction claire.', approachText: 'Une bonne ingénierie commence par une bonne conversation. Notre démarche est claire, collaborative et tournée vers votre prochaine étape.', startConversation: 'Commençons à échanger',
    step1Label: 'D’abord, l’écoute', step1Title: 'Comprendre votre ambition.', step1Text: 'Votre projet, vos priorités, vos défis. Nous commençons par poser les bonnes questions.', step2Label: 'Ensuite, le concret', step2Title: 'Définir un plan clair.', step2Text: 'Un périmètre partagé, des étapes concrètes et une vision commune du résultat attendu.', step3Label: 'Ensemble, on avance', step3Title: 'Réaliser avec soin.', step3Text: 'Une expertise de terrain, une communication ouverte et des réponses utiles à chaque étape.',
    aboutLabel: 'Celles et ceux qui font avancer les projets', aboutTitle1: 'Ancrés dans l’expertise.', aboutTitle2: 'Tournés vers demain.', aboutText: 'Basée à Grimbergen, en Belgique, Energy Experts BV propose des services de conception électrique, d’éolien en mer et d’énergie solaire. Notre objectif est simple : vous aider à avancer en confiance.', aboutAlt: 'Une sous-station électrique en mer', aboutPhotoLabel: 'Quand l’ingénierie rencontre les éléments.', value1: 'Des idées claires.', value2: 'Des solutions concrètes.', value3: 'Un engagement personnel.', meetUs: 'Faisons connaissance',
    contactLabel: 'Tout commence par une conversation', contactTitle1: 'Quel est', contactTitle2: 'votre horizon ?', contactText: 'Une idée, un défi technique ou un projet prêt à franchir une étape. Nous serions ravis d’en parler avec vous.', belgium: 'Belgique',
    formTitle: 'Parlez-nous un peu de votre projet.', formDemo: 'Formulaire de démonstration · Aucun envoi ni enregistrement', formName: 'Votre nom', formEmail: 'Adresse e-mail', formService: 'Comment pouvons-nous vous aider ?', serviceChoose: 'Choisir un service', serviceOther: 'Explorons les possibilités ensemble', formMessage: 'Quelques mots sur votre projet', formPrivacy: 'Cette démonstration reste dans votre navigateur.', sendPreview: 'Prévisualiser la demande', namePlaceholder: 'Alex Martin', emailPlaceholder: 'alex@entreprise.fr', messagePlaceholder: 'L’ambition, le lieu, la prochaine étape…', formSuccess: 'Votre aperçu est prêt. Sur le site final, cette demande serait transmise à Energy Experts. Rien n’a été envoyé ni enregistré.', formInvalid: 'Veuillez remplir tous les champs et décrire votre projet en au moins 10 caractères.',
    closing: 'Une meilleure énergie commence par le dialogue.', footerTagline: 'Un regard indépendant.\nUne énergie commune pour la suite.', footerConcept: '· Concept de site', backTop: 'En haut', privacyLink: 'Confidentialité', cookiesLink: 'Cookies', legalLink: 'Mentions légales', creditsLink: 'Crédits photo', closeDetails: 'Fermer les détails',
    projectScope: 'Exemple de prestations', projectDisclaimer: 'Projet purement illustratif. Le lieu, le récit et les prestations sont des exemples. Les photographies montrent des infrastructures réelles et ne prouvent pas une mission d’Energy Experts.', projectCta: 'Parlons d’un projet similaire', sampleLabel: 'Exemple de projet',
    privacyTitle: 'La confidentialité, simplement.', privacyText: 'Ceci est un aperçu local du design, et non la politique de confidentialité finale. Le formulaire vérifie uniquement les champs dans votre navigateur. Il ne transmet ni n’enregistre votre demande.', privacyText2: 'Ce concept ne contient aucun outil d’analyse, pixel publicitaire, carte intégrée ou police externe. La langue figure dans l’URL. Votre navigateur et un éventuel serveur de prévisualisation peuvent conserver un historique ou des journaux d’accès. Les liens e-mail et téléphone ouvrent l’application de votre choix.', privacyText3: 'Avant publication, l’entreprise doit approuver une politique précisant le responsable du traitement, les finalités, les bases légales, la conservation, les destinataires, les transferts internationaux et les droits applicables, dont la possibilité de déposer une plainte auprès de l’Autorité belge de protection des données.',
    cookiesTitle: 'Moins de suivi.\nPlus de confiance.', cookiesText: 'Ce concept ne dépose aucun cookie et n’utilise pas le stockage local. Il ne contient ni analyse d’audience, ni publicité, ni vidéo intégrée, ni carte externe. Les polices, scripts et photos sont servis avec la page.', cookiesText2: 'La langue choisie figure uniquement dans l’URL. Aucun bandeau de consentement n’est inclus, car cet aperçu n’utilise aucun traceur facultatif. L’hébergement final devra être vérifié avant d’afficher la même information sur le site public.', cookiesText3: 'Si des outils de suivi ou des contenus intégrés facultatifs sont ajoutés, leurs contrôles de consentement et informations de confidentialité devront être en place avant leur chargement.',
    legalTitle: 'Informations sur l’entreprise.', legalText: 'Energy Experts BV\nAlbrecht Rodenbachlaan 29\n1850 Grimbergen, Belgique\ninfo@energyexpertsbv.com\n+32 472 18 42 20', legalText2: 'Aperçu du design uniquement. Le nom et les coordonnées proviennent du site public existant et doivent être confirmés par le client. La dénomination légale, le numéro d’entreprise, le régime TVA et les mentions de registre applicables doivent être fournis avant publication.', legalText3: 'Les descriptions des services sont provisoires. Les projets sont illustratifs. Ce concept ne revendique aucune certification, relation client, expérience chiffrée ou performance.'
  },
  es: {
    skip: 'Ir al contenido', concept: 'HORIZON / Un concepto para Energy Experts BV', conceptNote: 'Contenido de muestra · Para comentar',
    navLabel: 'Navegación principal', mobileNav: 'Navegación móvil', navExpertise: 'Especialidades', navProjects: 'Proyectos', navApproach: 'Cómo trabajamos', navAbout: 'Nosotros', letsTalk: 'Hablemos', language: 'Elegir idioma', menuOpen: 'Abrir navegación', menuClose: 'Cerrar navegación', belgiumEurope: 'Desde Bélgica. Mirando al futuro.',
    heroLabel: 'Criterio independiente. Energía positiva.', heroLine1: 'Buena energía.', heroLine2: 'Gran experiencia.', heroText: 'Del primer plano a la última inspección. Ideas claras y experiencia práctica para un mundo con una energía diferente.', exploreExpertise: 'Descubre nuestra experiencia', heroScroll: 'Diseñamos un futuro mejor.', heroLocation: 'MAR DEL NORTE, BÉLGICA', heroAlt: 'Aerogeneradores en Thornton Bank, en el mar del Norte belga',
    sectorsLabel: 'Nuestros sectores', sectorCaption: 'Tres disciplinas. Un propósito claro.', sectorElectrical: 'Ingeniería eléctrica', sectorWind: 'Eólica marina', sectorSolar: 'Energía solar',
    introLabel: 'Progreso con propósito', introTitle1: 'Las grandes ambiciones', introTitle2: 'necesitan un apoyo firme.', introText: 'La energía está cambiando. Ayudamos a que ese cambio funcione: claridad en sistemas eléctricos complejos, confianza en proyectos marinos y atención en cada instalación solar.', meetExperts: 'Conócenos',
    expertiseLabel: '01 / Nuestra experiencia', expertiseTitle: 'Rigor técnico.\nSoluciones prácticas.', expertiseText: 'El conocimiento adecuado, justo donde importa. Descubre las disciplinas que dan forma a nuestro trabajo.',
    electricalTitle: 'Claridad en cada\nconexión.', electricalText: 'Diseño y clasificación con criterio para sistemas eléctricos seguros y eficientes.', electricalScope: 'Alcance de ejemplo: revisión de diseños, documentación técnica, evaluación de instalaciones y recomendaciones prácticas. Servicios definitivos por confirmar.',
    windTitle: 'Confianza más allá\nde la costa.', windText: 'Apoyo especializado para los retos de la energía eólica, desde la planificación hasta la operación.', windScope: 'Alcance de ejemplo: coordinación de proyectos, revisiones de calidad, inspecciones eléctricas y apoyo a la puesta en marcha. Servicios definitivos por confirmar.',
    solarTitle: 'Más certeza.\nEn cada rayo.', solarText: 'Inspecciones cuidadosas y consejos claros para que las instalaciones solares alcancen su potencial.', solarScope: 'Alcance de ejemplo: inspecciones visuales, revisiones de rendimiento, comprobación documental y propuestas de mejora. Servicios definitivos por confirmar.', serviceScope: 'Explorar el alcance', discussService: 'Hablemos de este servicio ↗',
    projectsLabel: '02 / Sobre el terreno', projectsTitle1: 'Experiencia en acción.', projectsTitle2: 'Impacto en camino.', projectsText: 'Cada proyecto tiene sus propios retos. Así podrían presentarse las historias de tus futuros proyectos.', sampleProjects: 'Proyectos ilustrativos', filterLabel: 'Filtrar proyectos', filterAll: 'Todos los proyectos', filterElectrical: 'Electricidad', projectNote: 'Una muestra de lo posible. Estas historias son ejemplos, no trabajos realizados para clientes.', projectCount: '{count} mostrados / 03', projectOpen: 'Explorar proyecto: ',
    approachLabel: '03 / Cómo trabajamos', approachTitle1: 'Proyectos complejos.', approachTitle2: 'Un camino claro.', approachText: 'La buena ingeniería empieza con una buena conversación. Trabajamos con claridad, colaboración y atención al siguiente paso.', startConversation: 'Empecemos a hablar',
    step1Label: 'Primero, escuchamos', step1Title: 'Entender la ambición.', step1Text: 'Tu proyecto, tus prioridades, tus retos. Empezamos haciendo las preguntas adecuadas.', step2Label: 'Después, concretamos', step2Title: 'Trazar un plan claro.', step2Text: 'Un alcance acordado, hitos prácticos y una visión compartida del resultado esperado.', step3Label: 'Juntos, avanzamos', step3Title: 'Entregar con cuidado.', step3Text: 'Experiencia sobre el terreno, comunicación abierta y respuestas útiles en cada etapa.',
    aboutLabel: 'Las personas detrás del progreso', aboutTitle1: 'Experiencia como base.', aboutTitle2: 'La mirada en el mañana.', aboutText: 'Desde Grimbergen, Bélgica, Energy Experts BV reúne servicios de diseño eléctrico, eólica marina y energía solar. Nuestro objetivo es sencillo: ayudarte a avanzar con confianza.', aboutAlt: 'Una subestación eléctrica en el mar', aboutPhotoLabel: 'Donde la ingeniería se encuentra con los elementos.', value1: 'Ideas claras.', value2: 'Soluciones prácticas.', value3: 'Compromiso personal.', meetUs: 'Vamos a conocernos',
    contactLabel: 'Todo empieza con una conversación', contactTitle1: '¿Qué hay en', contactTitle2: 'tu horizonte?', contactText: 'Una idea, un reto técnico o un proyecto listo para avanzar. Nos encantará conocerlo.', belgium: 'Bélgica',
    formTitle: 'Cuéntanos un poco sobre tu proyecto.', formDemo: 'Formulario de prueba · No se envían ni guardan datos', formName: 'Tu nombre', formEmail: 'Correo electrónico', formService: '¿Cómo podemos ayudarte?', serviceChoose: 'Elige un servicio', serviceOther: 'Exploremos las opciones juntos', formMessage: 'Unas palabras sobre tu proyecto', formPrivacy: 'Esta demostración permanece en tu navegador.', sendPreview: 'Previsualizar consulta', namePlaceholder: 'Álex García', emailPlaceholder: 'alex@empresa.es', messagePlaceholder: 'La ambición, la ubicación, el siguiente paso…', formSuccess: 'Tu vista previa está lista. En la web definitiva, esta consulta llegaría al equipo de Energy Experts. No se ha enviado ni guardado nada.', formInvalid: 'Completa todos los campos y describe tu proyecto con al menos 10 caracteres.',
    closing: 'Una mejor energía empieza con mejores conversaciones.', footerTagline: 'Criterio independiente.\nUna energía compartida para lo que viene.', footerConcept: '· Concepto de diseño', backTop: 'Volver arriba', privacyLink: 'Privacidad', cookiesLink: 'Cookies', legalLink: 'Aviso legal', creditsLink: 'Créditos fotográficos', closeDetails: 'Cerrar detalles',
    projectScope: 'Alcance de ejemplo', projectDisclaimer: 'Proyecto únicamente ilustrativo. La ubicación, la historia y el alcance son ejemplos. Las fotografías muestran infraestructuras reales y no implican un encargo de Energy Experts.', projectCta: 'Hablemos de un proyecto similar', sampleLabel: 'Proyecto de ejemplo',
    privacyTitle: 'Privacidad, sin complicaciones.', privacyText: 'Esta es una vista previa local del diseño, no la política de privacidad definitiva. El formulario solo valida los campos en tu navegador. No tiene un servicio de envío y no transmite ni guarda tu consulta.', privacyText2: 'Este concepto no incluye analítica, píxeles publicitarios, mapas integrados ni fuentes externas. El idioma se indica en la URL. Tu navegador y cualquier servidor de vista previa pueden conservar el historial o registros de acceso. Los enlaces de correo y teléfono abren la aplicación que elijas.', privacyText3: 'Antes de publicar, la empresa debe aprobar una política que identifique al responsable, las finalidades, las bases jurídicas, la conservación, los destinatarios, las transferencias internacionales y los derechos aplicables, incluido cómo reclamar ante la Autoridad belga de Protección de Datos.',
    cookiesTitle: 'Menos seguimiento.\nMás confianza.', cookiesText: 'Este concepto no utiliza cookies ni almacenamiento local. No incluye analítica, publicidad, vídeos integrados ni mapas externos. Las fuentes, los scripts y las fotografías se sirven con la página.', cookiesText2: 'El idioma elegido solo se indica en la URL. No hay un banner de consentimiento porque esta vista previa no utiliza seguimiento opcional. Hay que comprobar el alojamiento definitivo antes de hacer la misma afirmación en la web publicada.', cookiesText3: 'Si más adelante se añaden herramientas de seguimiento o contenidos integrados opcionales, sus controles de consentimiento y su información de privacidad deberán estar disponibles antes de cargarlos.',
    legalTitle: 'Datos de la empresa.', legalText: 'Energy Experts BV\nAlbrecht Rodenbachlaan 29\n1850 Grimbergen, Bélgica\ninfo@energyexpertsbv.com\n+32 472 18 42 20', legalText2: 'Solo una vista previa. El nombre y los datos de contacto proceden de la web pública actual y requieren confirmación del cliente. Antes de publicar deben facilitarse la razón social, el número de empresa, la situación del IVA y los datos registrales aplicables.', legalText3: 'Las descripciones de servicios son provisionales. Los proyectos son ilustrativos. Este concepto no afirma certificaciones, relaciones con clientes, experiencia cuantificada ni cifras de rendimiento.'
  }
};

const HORIZON_PROJECTS = [
  {
    id: 'north-sea', category: 'wind', image: 'img/wind-norther.jpg',
    en: { title: 'A clearer course for offshore wind.', location: 'North Sea', category: 'Offshore wind', alt: 'Aerial view of wind turbines and their wakes at Norther wind farm', description: 'An illustrative story about supporting a wind energy project at sea. This space will explain the client’s challenge, the role of Energy Experts, and the difference the team made — in plain language.', scope: ['Define the technical requirements with the project team.', 'Coordinate reviews and document practical findings.', 'Support the next stage with a clear handover.'] },
    fr: { title: 'Un cap plus clair pour l’éolien en mer.', location: 'Mer du Nord', category: 'Éolien en mer', alt: 'Vue aérienne des éoliennes et de leurs sillages au parc Norther', description: 'Un exemple de récit sur l’accompagnement d’un projet éolien en mer. Cet espace présentera le défi du client, le rôle d’Energy Experts et la contribution de l’équipe, dans un langage accessible.', scope: ['Définir les exigences techniques avec l’équipe projet.', 'Coordonner les revues et documenter les constats.', 'Préparer la prochaine étape avec une transmission claire.'] },
    es: { title: 'Un rumbo más claro para la eólica marina.', location: 'Mar del Norte', category: 'Eólica marina', alt: 'Vista aérea de los aerogeneradores y sus estelas en el parque Norther', description: 'Una historia de ejemplo sobre el apoyo a un proyecto eólico en el mar. Este espacio explicará el reto del cliente, el papel de Energy Experts y la aportación del equipo, con un lenguaje claro.', scope: ['Definir los requisitos técnicos con el equipo del proyecto.', 'Coordinar revisiones y documentar los hallazgos.', 'Preparar el siguiente paso con una entrega clara.'] }
  },
  {
    id: 'solar-field', category: 'solar', image: 'img/solar-dulmen.jpg',
    en: { title: 'Bringing potential to light.', location: 'European solar', category: 'Solar energy', alt: 'Rows of photovoltaic solar panels in a green field', description: 'An example of how a solar inspection story could be told. The final case study will describe a real installation, the questions that needed answering, and the recommendations delivered by the team.', scope: ['Understand the installation and its operating context.', 'Review the condition and available documentation.', 'Present useful findings and recommended next steps.'] },
    fr: { title: 'Révéler tout le potentiel du solaire.', location: 'Solaire en Europe', category: 'Énergie solaire', alt: 'Rangées de panneaux photovoltaïques dans un champ', description: 'Un exemple de présentation d’une inspection solaire. L’étude de cas finale décrira une installation réelle, les questions à résoudre et les recommandations de l’équipe.', scope: ['Comprendre l’installation et son contexte d’exploitation.', 'Examiner son état et la documentation disponible.', 'Présenter les constats utiles et les prochaines étapes.'] },
    es: { title: 'Sacar a la luz todo el potencial.', location: 'Solar en Europa', category: 'Energía solar', alt: 'Filas de paneles fotovoltaicos en un campo verde', description: 'Un ejemplo de cómo presentar una inspección solar. El caso definitivo describirá una instalación real, las cuestiones por resolver y las recomendaciones del equipo.', scope: ['Entender la instalación y su contexto operativo.', 'Revisar su estado y la documentación disponible.', 'Presentar hallazgos útiles y los siguientes pasos.'] }
  },
  {
    id: 'electrical-design', category: 'electrical', image: 'img/hv-switchgear-4.jpg',
    en: { title: 'Confidence, connected.', location: 'Electrical systems', category: 'Electrical engineering', alt: 'High-voltage switchgear and electrical infrastructure', description: 'A sample project about bringing clarity to an electrical installation. Replace this story with the actual scope, approved photographs, and outcomes the client is comfortable sharing publicly.', scope: ['Review the design and installation requirements.', 'Identify points that need clarification or improvement.', 'Deliver practical guidance and structured documentation.'] },
    fr: { title: 'La confiance, à chaque connexion.', location: 'Systèmes électriques', category: 'Ingénierie électrique', alt: 'Appareillage haute tension et infrastructure électrique', description: 'Un exemple de projet visant à clarifier une installation électrique. Ce récit sera remplacé par le périmètre réel, des photos approuvées et des résultats que le client souhaite partager.', scope: ['Examiner la conception et les exigences de l’installation.', 'Identifier les points à préciser ou à améliorer.', 'Fournir des conseils pratiques et une documentation structurée.'] },
    es: { title: 'Conectados con confianza.', location: 'Sistemas eléctricos', category: 'Ingeniería eléctrica', alt: 'Aparamenta de alta tensión e infraestructura eléctrica', description: 'Un proyecto de muestra sobre cómo aportar claridad a una instalación eléctrica. Se sustituirá por el alcance real, fotografías aprobadas y resultados que el cliente desee compartir.', scope: ['Revisar el diseño y los requisitos de la instalación.', 'Identificar aspectos que necesitan aclaración o mejora.', 'Entregar orientación práctica y documentación estructurada.'] }
  }
];

/* ---- added: theme toggle + storage consent (parity with designs 1-4) ---- */
Object.assign(HORIZON_COPY.en, {
  themeToggle: 'Switch between light and dark',
  themeLight: 'Light', themeDark: 'Dark',
  consentTitle: 'A note on what this site stores',
  consentText: 'Horizon sets no cookies and loads nothing from other companies. We would only like to remember your language and light or dark choice in this browser, so the site looks the same next time.',
  consentAccept: 'Remember my choices', consentReject: 'Do not store anything',
  consentMore: 'What this means',
  consentSavedOn: 'Your language and theme are remembered in this browser.',
  consentSavedOff: 'Nothing is stored. Your choices reset when you close the tab.',
  designSwitch: 'Design 5 of 5', designPrev: 'Previous design', designNext: 'Next design', designAll: 'All designs'
});
Object.assign(HORIZON_COPY.fr, {
  themeToggle: 'Basculer entre le mode clair et sombre',
  themeLight: 'Clair', themeDark: 'Sombre',
  consentTitle: 'Ce que ce site conserve',
  consentText: 'Horizon ne dépose aucun cookie et ne charge rien provenant d’autres sociétés. Nous souhaitons seulement mémoriser votre langue et votre choix clair ou sombre dans ce navigateur, afin que le site soit identique à votre prochaine visite.',
  consentAccept: 'Mémoriser mes choix', consentReject: 'Ne rien conserver',
  consentMore: 'Ce que cela signifie',
  consentSavedOn: 'Votre langue et votre thème sont mémorisés dans ce navigateur.',
  consentSavedOff: 'Rien n’est conservé. Vos choix seront réinitialisés à la fermeture de l’onglet.',
  designSwitch: 'Design 5 sur 5', designPrev: 'Design précédent', designNext: 'Design suivant', designAll: 'Tous les designs'
});
Object.assign(HORIZON_COPY.es, {
  themeToggle: 'Cambiar entre modo claro y oscuro',
  themeLight: 'Claro', themeDark: 'Oscuro',
  consentTitle: 'Qué guarda este sitio',
  consentText: 'Horizon no instala cookies ni carga nada de otras empresas. Solo querríamos recordar su idioma y su elección de modo claro u oscuro en este navegador, para que el sitio se vea igual la próxima vez.',
  consentAccept: 'Recordar mis preferencias', consentReject: 'No guardar nada',
  consentMore: 'Qué significa esto',
  consentSavedOn: 'Su idioma y su tema se recuerdan en este navegador.',
  consentSavedOff: 'No se guarda nada. Sus preferencias se restablecen al cerrar la pestaña.',
  designSwitch: 'Diseño 5 de 5', designPrev: 'Diseño anterior', designNext: 'Diseño siguiente', designAll: 'Todos los diseños'
});
